### ISSUE TITLE
Error at npm install

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-node#268]
After cloning the repository, and running `npm i` I get:

```
[...]

Build finished successfully.
  CXX(target) Release/obj.target/libbitcoind/src/libbitcoind.o
../src/libbitcoind.cc:102:8: error: unknown type name 'Eternal'
static Eternal<Function> txmon_callback;
       ^
../src/libbitcoind.cc:102:15: error: expected unqualified-id
static Eternal<Function> txmon_callback;
              ^
../src/libbitcoind.cc:232:31: error: call to 'Null' is ambiguous
    info.GetReturnValue().Set(Null());
                              ^~~~
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:2619:28: note: candidate function
Handle<Primitive> V8EXPORT Null();
                           ^
../node_modules/nan/nan.h:909:39: note: candidate function
  NAN_INLINE v8::Local<v8::Primitive> Null() {
                                      ^
../src/libbitcoind.cc:250:3: error: use of undeclared identifier 'Eternal'
  Eternal<Function> cb(isolate, callback);
  ^
../src/libbitcoind.cc:250:11: error: 'Function' does not refer to a value
  Eternal<Function> cb(isolate, callback);
          ^
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:1774:7: note: declared here
class Function : public Object {
      ^
../src/libbitcoind.cc:250:21: error: use of undeclared identifier 'cb'
  Eternal<Function> cb(isolate, callback);
                    ^
../src/libbitcoind.cc:251:3: error: use of undeclared identifier 'txmon_callback'
  txmon_callback = cb;
  ^
../src/libbitcoind.cc:251:20: error: use of undeclared identifier 'cb'
  txmon_callback = cb;
                   ^
../src/libbitcoind.cc:257:3: error: no matching function for call to 'uv_async_init'
  uv_async_init(uv_default_loop(), &txmon_async, tx_notifier);
  ^~~~~~~~~~~~~
/Users/ematiu/.node-gyp/0.10.29/deps/uv/include/uv.h:1192:15: note: candidate function
      not viable: no known conversion from 'void (uv_async_t *)' to 'uv_async_cb' (aka
      'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
              ^
../src/libbitcoind.cc:259:29: error: call to 'Null' is ambiguous
  info.GetReturnValue().Set(Null());
                            ^~~~
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:2619:28: note: candidate function
Handle<Primitive> V8EXPORT Null();
                           ^
../node_modules/nan/nan.h:909:39: note: candidate function
  NAN_INLINE v8::Local<v8::Primitive> Null() {
                                      ^
../src/libbitcoind.cc:264:43: error: no member named 'GetIsolate' in 'v8::Context'
  Isolate* isolate = GetCurrentContext()->GetIsolate();
                     ~~~~~~~~~~~~~~~~~~~  ^
../src/libbitcoind.cc:265:15: error: no matching constructor for initialization of
      'v8::HandleScope'
  HandleScope scope(isolate);
              ^     ~~~~~~~
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:473:3: note: candidate constructor
      not viable: no known conversion from 'v8::Isolate *' to 'const v8::HandleScope'
      for 1st argument
  HandleScope(const HandleScope&);
  ^
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:448:3: note: candidate constructor
      not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../src/libbitcoind.cc:267:37: error: cannot initialize a parameter of type 'int' with an
      lvalue of type 'v8::Isolate *'
  Local<Array> results = Array::New(isolate);
                                    ^~~~~~~
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:1762:40: note: passing argument to
      parameter 'length' here
  V8EXPORT static Local<Array> New(int length = 0);
                                       ^
../src/libbitcoind.cc:276:29: error: no matching function for call to 'New'
    Local<Value> txBuffer = node::Buffer::New(isolate, stx.c_str(), stx.size());
                            ^~~~~~~~~~~~~~~~~
/Users/ematiu/.node-gyp/0.10.29/src/node_buffer.h:123:18: note: candidate function not
      viable: requires 2 arguments, but 3 were provided
  static Buffer* New(const char *data, size_t len);
                 ^
/Users/ematiu/.node-gyp/0.10.29/src/node_buffer.h:125:18: note: candidate function not
      viable: requires 4 arguments, but 3 were provided
  static Buffer* New(char *data, size_t length,
                 ^
/Users/ematiu/.node-gyp/0.10.29/src/node_buffer.h:116:33: note: candidate function not
      viable: requires single argument 'string', but 3 arguments were provided
  static v8::Handle<v8::Object> New(v8::Handle<v8::String> string);
                                ^
/Users/ematiu/.node-gyp/0.10.29/src/node_buffer.h:121:18: note: candidate function not
      viable: requires single argument 'length', but 3 arguments were provided
  static Buffer* New(size_t length);
                 ^
/Users/ematiu/.node-gyp/0.10.29/src/node_buffer.h:129:32: note: candidate function not
      viable: requires single argument 'args', but 3 arguments were provided
  static v8::Handle<v8::Value> New(const v8::Arguments &args);
                               ^
../src/libbitcoind.cc:292:5: error: too many arguments to function call, expected 1,
      have 2; did you mean '::New'?
    Local<Value>::New(isolate, results)
    ^~~~~
    ::New
../node_modules/nan/nan.h:284:14: note: '::New' declared here
v8::Local<T> New(v8::Handle<T>);
             ^
../src/libbitcoind.cc:295:24: error: use of undeclared identifier 'txmon_callback'
  Local<Function> cb = txmon_callback.Get(isolate);
                       ^
../src/libbitcoind.cc:297:21: error: no member named 'GetCurrentContext' in
      'v8::Isolate'
  cb->Call(isolate->GetCurrentContext()->Global(), argc, argv);
           ~~~~~~~  ^
../src/libbitcoind.cc:316:15: error: no matching constructor for initialization of
      'v8::HandleScope'
  HandleScope scope(isolate);
              ^     ~~~~~~~
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:473:3: note: candidate constructor
      not viable: no known conversion from 'v8::Isolate *' to 'const v8::HandleScope'
      for 1st argument
  HandleScope(const HandleScope&);
  ^
/Users/ematiu/.node-gyp/0.10.29/deps/v8/include/v8.h:448:3: note: candidate constructor
      not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../src/libbitcoind.cc:321:17: error: no member named 'Reset' in
      'v8::Persistent<v8::Function>'
  req->callback.Reset(isolate, callback);
  ~~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/libbitcoind/src/libbitcoind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /Users/ematiu/devel/bitcore-node
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 

npm ERR! bitcore-node@0.2.0-dev install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@0.2.0-dev install script.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "i"
npm ERR! cwd /Users/ematiu/devel/bitcore-node
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.5.0-alpha-4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ematiu/devel/bitcore-node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by braydonf** [comment]
Node v0.10.29 isn't supported. Switching to v0.12 with  `nvm use v0.12.7` should fix the issue.

**Comment by matiu** [comment]
worked with `n` and 0.12.17.

thanks!
