### ISSUE TITLE
Error during CLI command

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#281]
**Steps to reproduce:**

1. Start up a node on livenet
2. Run the command `bitcore-node call getTransaction 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098`

**Error message details:**
```js
Missing error handler on `socket`.
Error: Usage: daemon.getTransaction(txid, queryMempool, callback)
    at Error (native)
    at Bitcoin.getTransaction (/home/braydon/bitcore-node/lib/services/bitcoind.js:265:19)
    at DB.getTransaction (/home/braydon/bitcore-node/lib/services/db.js:323:31)
    at self.methodsMap.(anonymous function).fn (/home/braydon/bitcore-node/lib/services/web.js:117:23)
    at WebService.socketMessageHandler (/home/braydon/bitcore-node/lib/services/web.js:228:40)
    at Socket.emit (events.js:110:17)
    at Socket.onevent (/home/braydon/bitcore-node/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/braydon/bitcore-node/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/braydon/bitcore-node/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/braydon/bitcore-node/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
```

**Comment by braydonf** [comment]
Merging with https://github.com/bitpay/bitcore-node/issues/291
