### ISSUE TITLE
Undefined error in a block page

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/bitcore-node#285]
Opening this block with insight-ui: `000000000000000001e6ba26d1bba500d9cbd6fc30e853730376f20c1b7837e1` 

It gives an error (and shutdown bitcore-node):

```
{bitcore-node} error: uncaught exception: [TypeError: undefined is not a function]
{bitcore-node} error: TypeError: undefined is not a function
    at TxController.transformOutput (/home/bitcoind/mynode/node_modules/insight-api/lib/transactions.js:179:30)
    at /home/bitcoind/mynode/node_modules/insight-api/lib/transactions.js:85:12
    at /home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:358:13
    at /home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:239:13
    at _arrayEach (/home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:91:13)
    at _each (/home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:82:13)
    at async.forEachOf.async.eachOf (/home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:238:9)
    at _asyncMap (/home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:357:9)
    at Object.map (/home/bitcoind/mynode/node_modules/insight-api/node_modules/async/lib/async.js:340:20)
    at TxController.transformTransaction (/home/bitcoind/mynode/node_modules/insight-api/lib/transactions.js:80:9)
```

**Comment by braydonf** [comment]
Current insight-ui and insight-api are build against the latest development version and requires a building bitcore-node. The `getInputForOutput()` method was recently added. The next build, available each Wednesday, will include this method.

**Comment by braydonf** [comment]
Will be fixed with release: https://github.com/bitpay/bitcore-node/releases/tag/v0.2.0-beta.10
