### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by cevin** [bitpay/bitcore-node#287]
```
/usr/local/node/lib/node_modules/bitcore-node/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by braydonf** [comment]
This is likely an Node.js version compatibility issue. Are you running Node.js v0.12?

**Comment by cevin** [comment]
@braydonf v4.1.2

**Comment by braydonf** [comment]
Node.js v0.12 is currently supported. Here is the issue for adding Node.js v4 support: https://github.com/bitpay/bitcore-node/issues/259

**Comment by cevin** [comment]
@braydonf thks. please close this issue.
