### ISSUE TITLE
Error when sending a transaction with BWS and Bitcore Node

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#294]
I haven't been able to verify the condition that will cause this error yet, however these may be steps to reproduce on testnet: 

- Send 1BTC to Copay wallet
- Immediately send 1BTC back to source (unconfirmed transaction)

```
ERR! Error building Bitcore transaction Error: Invalid outputIndex, received undefined
ERR! Error building Bitcore transaction     at new UnspentOutput (/home/braydon/bitcore/lib/transaction/unspentoutput.js:42:11)
ERR! Error building Bitcore transaction     at Transaction._fromMultisigUtxo (/home/braydon/bitcore/lib/transaction/transaction.js:571:10)
ERR! Error building Bitcore transaction     at Transaction.from (/home/braydon/bitcore/lib/transaction/transaction.js:540:10)
ERR! Error building Bitcore transaction     at /home/braydon/mynode/node_modules/bitcore-wallet-service/node_modules/bitcore-wallet-utils/lib/walletutils.js:196:11
ERR! Error building Bitcore transaction     at arrayEach (/home/braydon/mynode/node_modules/bitcore-wallet-service/node_modules/lodash/index.js:1289:13)
ERR! Error building Bitcore transaction     at Function.<anonymous> (/home/braydon/mynode/node_modules/bitcore-wallet-service/node_modules/lodash/index.js:3345:13)
ERR! Error building Bitcore transaction     at Function.WalletUtils.buildTx (/home/braydon/mynode/node_modules/bitcore-wallet-service/node_modules/bitcore-wallet-utils/lib/walletutils.js:195:9)
ERR! Error building Bitcore transaction     at TxProposal.getBitcoreTx (/home/braydon/mynode/node_modules/bitcore-wallet-service/lib/model/txproposal.js:167:23)
ERR! Error building Bitcore transaction     at /home/braydon/mynode/node_modules/bitcore-wallet-service/lib/server.js:1061:27
ERR! Error building Bitcore transaction     at /home/braydon/mynode/node_modules/bitcore-wallet-service/lib/server.js:828:16
ERR! Error building Bitcore transaction  [Error: Invalid outputIndex, received undefined]
ERR! /v1/txproposals/ :undefined:Invalid outputIndex, received undefined 
```

**Comment by kleetus** [comment]
I did this with 2 Copay wallets, one on Android and one was the Copay Mac app on testnet. All seemed to work. I will keep trying.

**Comment by braydonf** [comment]
If I see it again, I'll post the steps.

**Comment by braydonf** [comment]
Finally tracked down what was causing this issue, and there is a fix here: https://github.com/bitpay/bitcore-node/pull/307
