### ISSUE TITLE
Build error regarding boost

### ISSUE THREAD

**Issue by unusualbob** [bitpay/bitcore-node#296]
```
brew install autoconf automake libtool openssl pkg-config
Warning: autoconf-2.69 already installed
Warning: automake-1.15 already installed
Warning: libtool-2.4.6 already installed
Warning: openssl-1.0.2d_1 already installed
Warning: pkg-config-0.28 already installed
```

```
node --version
v0.12.7
```

```sh
npm install
<snip>
checking whether strnlen is declared... yes
checking whether le16toh is declared... no
checking whether le32toh is declared... no
checking whether le64toh is declared... no
checking whether htole16 is declared... no
checking whether htole32 is declared... no
checking whether htole64 is declared... no
checking whether be16toh is declared... no
checking whether be32toh is declared... no
checking whether be64toh is declared... no
checking whether htobe16 is declared... no
checking whether htobe32 is declared... no
checking whether htobe64 is declared... no
checking whether bswap_16 is declared... no
checking whether bswap_32 is declared... no
checking whether bswap_64 is declared... no
checking for MSG_NOSIGNAL... no
checking for library containing clock_gettime... no
checking for visibility attribute... yes
checking whether to compile as daemonlib... yes
checking whether to build Bitcoin Core GUI... no (Qt)
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the boost_system library!
make V=1
make: *** No targets specified and no makefile found.  Stop.
Creating the sha marker for the patching in libbitcoind...
Writing patch sha file to: "/Users/xxx/xxx/bitcore-node/bin/../cache/patch_sha.txt"
~/xxx/bitcore-node/libbitcoind ~/xxx/bitcore-node/libbitcoind
~/xxx/bitcore-node/libbitcoind
Build finished successfully.
  CXX(target) Release/obj.target/libbitcoind/src/libbitcoind.o
In file included from ../src/libbitcoind.cc:9:
In file included from ../src/libbitcoind.h:1:
In file included from /Users/xxx/xxx/bitcore-node/cache/src/main.h:14:
/Users/xxx/xxx/bitcore-node/cache/src/chain.h:17:10: fatal error: 'boost/foreach.hpp' file not found
#include <boost/foreach.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/libbitcoind/src/libbitcoind.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /Users/xxx/xxx/bitcore-node
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@0.2.0-dev install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@0.2.0-dev install script './bin/install'.
```

**Comment by unusualbob** [comment]
Oh and just for more info: 
```
brew install boost
Warning: boost-1.58.0 already installed
```

**Comment by unusualbob** [comment]
Oh also just noticed this:
```
Downloading binary: https://bitcore-node.s3.amazonaws.com/libbitcoind-0.2.0-dev-darwin-x64.tgz
curl: (22) The requested URL returned error: 404 Not Found
Prebuild binary could not be downloaded, building from source...
```

**Comment by unusualbob** [comment]
Welp, checking out 0.2 beta 10 seems to work as its download succeeds and I don't have to compile from source. May want to make sure that libbitcoind compilation is properl

**Comment by kleetus** [comment]
all the dependencies come from bitcoin itself now in the depends directory, there is no need to install anything from brew. Xcode and command line tools are still necessary if using a Mac. I can't see from the build output, but I suspect that the boost download failed. This happens from time to time. I will update the build.md about this and correct the build scripts in order to fail immediately if the download fails.
