### ISSUE TITLE
Error: Cannot find module 'bn.js'

### ISSUE THREAD

**Issue by cevin** [bitpay/bitcore-node#297]
```
> bitcore-node@0.2.0-dev start /data/bitcore-node
> node bin/start.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'bn.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/data/bitcore-node/node_modules/bitcore/lib/crypto/bn.js:3:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@0.2.0-dev start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@0.2.0-dev start script 'node bin/start.js'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/bitcore-node/npm-debug.log
```

from node-v4

**Comment by braydonf** [comment]
It's likely that you don't have dependencies installed. 

It's not clear how you're installing, however if you've git cloned, make sure to checkout the tag `v0.2.0-beta.10` and run `npm install` within the cloned project, or if you would like to compile from source use the build documentation: https://github.com/bitpay/bitcore-node/blob/master/docs/build.md

Otherwise you can see the documentation on getting started: https://github.com/bitpay/bitcore-node#install

**Comment by cevin** [comment]
@braydonf  thks, I try to cloned and run `npm install -g --unsafe-perm` and installed, awaiting for testing.

**Comment by braydonf** [comment]
Many tests are not working yet on that branch.

**Comment by cevin** [comment]
@braydonf   oh my god  -_-!

How to install nodejs v0.10  -_-!  I'm a php dever.

**Comment by cevin** [comment]
@braydonf 

```
/data/bitcore-node# npm install -g
 
> utf-8-validate@1.2.1 install /root/.nvm/versions/node/v0.12.7/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
 
> bufferutil@1.2.1 install /root/.nvm/versions/node/v0.12.7/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

```

**Comment by braydonf** [comment]
I recommend installing nvm as a user, instead of as root.

**Comment by pnagurny** [comment]
See this as well: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by cevin** [comment]
@braydonf 

Create a new user `nvm` and reinstall nvm and re-clone bitcore-node.
npm install error:

```
> utf-8-validate@1.2.1 install /home/nvm/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn ENOMEM
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:1162:11)
gyp ERR! stack     at Object.exports.spawn (child_process.js:995:9)
gyp ERR! stack     at Gyp.spawn (/home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:186:26)
gyp ERR! stack     at doBuild (/home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:259:20)
gyp ERR! stack     at copyNodeLib (/home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:181:37)
gyp ERR! stack     at /home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:111:7
gyp ERR! stack     at /home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/which/which.js:81:18
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
ERR! System Linux 3.13.0-65-generic
gyp ERR! command "node" "/home/nvm/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nvm/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
```

**Comment by braydonf** [comment]
Outdated now, please let us know if there are any other issues.
