### ISSUE TITLE
LMDB support

### ISSUE THREAD

**Issue by vincentmele** [bitpay/bitcore-node#359]
(This is my first attempt at contributing back to an established project and I am by no means a node programmer.)

I have updated a leveldown compatible LMDB library and have had success building and starting bitcore-node with it. However, I am running into memory errors after a while of the bitcore-node building its database: "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory". This happened on a dedicated server with 64 GB of RAM.

See: https://github.com/vincentmele/bitcore-node/tree/lmdb and https://github.com/vincentmele/lmdb

**Comment by kleetus** [comment]
admittedly, I am not an expert on LMDB, but it looks pretty interesting as I look at the project. I checked out the patch between bitpay/bitcore-node master and your lmdb branch and it is surprisingly small. I think with some tuning and a few hours with valgrind, this can be some thing fixable.

**Comment by StinkiePhish** [comment]
I have heard great things about LMDB being a good replacement for LevelDB due to its read performance, and my goal is to get it working with bitcore-node so that it can be benchmarked.

At least as to the error I cited above, changing `"start": "node bin/start.js"`to `"start": "node --max-old-space-size=8192 bin/start.js"` in the bitcore-node/package.json appears to have allowed bitcore-node to avoid the error (for the time being). 

Block parsing is slow at 0.4 to 1.7 blocks per second near mainnet block 208500.

Insight is crashing if I click an address in a block, but this is definitely an error caused by the lmdb leveldown module:
```
[2015-11-11T19:07:56.776Z] error: uncaught exception: [RangeError: index out of range]
[2015-11-11T19:07:56.784Z] error: RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt32BE (buffer.js:580:5)
    at BufferReader.readUInt32BE (/home/vince/bitcore-node/node_modules/bitcore-lib/lib/encoding/bufferreader.js:75:22)
    at AddressService._decodeInputKey (/home/vince/bitcore-node/lib/services/address/index.js:634:23)
    at ReadStream.<anonymous> (/home/vince/bitcore-node/lib/services/address/index.js:962:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (/home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ReadStream.Readable.push (/home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at /home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/index.js:40:12
[2015-11-11T19:07:56.786Z] info: Beginning shutdown
[2015-11-11T19:07:56.787Z] info: Stopping insight-ui
[2015-11-11T19:07:56.788Z] error: uncaught exception: [RangeError: index out of range]
[2015-11-11T19:07:56.792Z] error: RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt32BE (buffer.js:580:5)
    at BufferReader.readUInt32BE (/home/vince/bitcore-node/node_modules/bitcore-lib/lib/encoding/bufferreader.js:75:22)
    at AddressService._decodeOutputKey (/home/vince/bitcore-node/lib/services/address/index.js:587:23)
    at ReadStream.<anonymous> (/home/vince/bitcore-node/lib/services/address/index.js:1144:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (/home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ReadStream.Readable.push (/home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at /home/vince/bitcore-node/node_modules/levelup/node_modules/level-iterator-stream/index.js:40:12
```

I will keep at it, but I don't have the expertise to get very deep.

**Comment by kleetus** [comment]
I did some reading about LMDB last evening. Very interesting work. This could be really great for bitcore. It seems like this might be an interesting candidate for the replacement to LevelDB (at least in bitcore), which does not seem to have the support of the original authors at Google. I need to delve into this DB very soon.

**Comment by StinkiePhish** [comment]
The error above regarding insight and the iterators has been squashed by merging in another one of the forks of rvagg's project. It looks like it "works," but still likely has some LMDB related memory issues (probably not related to the memory issue I originally cited). LMDB uses everything it can get its hands on; that's not an abnormality. However, even though I have turned swappiness down to 0 in Ubuntu, after 12-14 hours or so it starts swapping anyways.

I will continue to proceed with parsing mainnet. It looks like it may be a total of 3-4 days of processing on a single non-RAID SSD. This is a typical output of `iostat 5` processing 0.4 to 1 block per second near block number 226545:
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.73    0.41   10.63   10.74    0.00   70.49

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               0.00         0.00         0.00          0          0
sdb            4488.40     59472.80     10120.80     297364      50604
dm-0              0.00         0.00         0.00          0          0
dm-1              0.00         0.00         0.00          0          0
scd0              0.00         0.00         0.00          0          0
```

**Comment by STRML** [comment]
@vincentmele How'd it go? Interested in this fork and anything we can do to increase bitcore's performance.

**Comment by braydonf** [comment]
I took a look into LMDB with several tests, and using [node-lmdb](https://github.com/Venemo/node-lmdb) library (and adhering to the zero-copy promise of LMDB) looks to be promising option. Being able to run separate processes is an advantage, however with LevelDB multiple threads will be used. If the event loop isn't blocked, there shouldn't be huge performance benefits there. There is a downside though, writing is slower the larger the key space, especially in comparison with batch writes for LevelDB. Using [LSM](https://en.wikipedia.org/wiki/Log-structured_merge-tree) is appealing for block indexes over a B+ tree in that regard, and likely why it's heavily used in many bitcoin and cryptocurrency implementations.

**Comment by martindale** [comment]
@STRML I'd be very interested to hear where you're using Bitcore and what performance bottlenecks you are seeing?  Excited to see real volume somewhere.  LMDB looks exciting, but I'm not sure of the implications for a blockchain's load profile.

**Comment by braydonf** [comment]
Data and indexes are a part of bitcoind now.
