### ISSUE TITLE
Installs fine in Node.js v4.2 but not v0.12 (Debian, NVM)

### ISSUE THREAD

**Issue by Jamesinatr** [bitpay/bitcore-node#367]
Bitcore-node claims to work on versions 0.12 and 4.2 of Node.js.

However, when using node.js v0.12.8 (nvm install v0.12), I get the following error in the terminal after typing `npm install -g bitcore-node`:
```
admin@instance-2:~$ npm install -g bitcore-node
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1016:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1184:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:484:11)
npm WARN addRemoteGit  bitpay/socket.io#bitpay-1.3.7 resetting remote /home/admin/.npm/_git-remotes/git-github-c
om-bitpay-socket-io-git-2b6acbb0 because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1016:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1184:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:484:11)
npm WARN addRemoteGit  bitpay/socket.io-client#bitpay-1.3.7 resetting remote /home/admin/.npm/_git-remotes/git-g
ithub-com-bitpay-socket-io-client-git-01902db7 because of error: { [Error: Command failed: git config --get remo
te.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
```
On Node.js version 4.2, it installs with no errors.

I'm using a fresh install of the latest Debian with git installed via apt-get and no other packages of significance.

Is this an issue or just a problem with my config? I'm fine with using 4.2, I just don't know why this is randomly happening now when it worked a few days ago. Maybe you should fix this if it's a problemn for everyone?

**Comment by braydonf** [comment]
That looks like an issue generated from npm while cloning `bitpay/socket.io#bitpay-1.3.7`, tried the install here with Node.js 0.12.8 and it worked.
