### ISSUE TITLE
Issue building [Ubuntu 14.04, Node 0.12.9]

### ISSUE THREAD

**Issue by samuraisam** [bitpay/bitcore-node#371]
I'm trying to build bitcore-node, but getting the following error when doing so:

```
make: Entering directory `/home/ubuntu/node/node_modules/bitcore-node/build'
make: *** No rule to make target `Release/obj.target/libbitcoind/src/libbitcoind.o', needed by `Release/obj.target/bitcoind.node'.  Stop.
make: Leaving directory `/home/ubuntu/node/node_modules/bitcore-node/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /home/ubuntu/node/node_modules/bitcore-node
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
```
I have all the relevant dependencies and whatnot installed on this machine - there seems to be an issue with the libbitcoind makefile

**Comment by braydonf** [comment]
There may have been a previous error during the build, can you check the log?

**Comment by samuraisam** [comment]
It seems to be a way that gyp works when installing using `npm install <repo>` - when cloning the repo and running `npm install` in itself, it works just fine

**Comment by braydonf** [comment]
Build process is different now, and a `Release/obj.target/bitcoind.node` isn't built via npm install. Instead `bitcoind` (with additional indexes) is started as a child process.
