### ISSUE TITLE
Global (`npm install -g`) build fails on Debian Jessie with `BITCORENODE_ENV=test`

### ISSUE THREAD

**Issue by posita** [bitpay/bitcore-node#385]
[`npm-debug.log` here](https://gist.githubusercontent.com/posita/c010c9980ce3e05f96ad/raw/e09b11568389b8e9aa9f0706e85f74465996d4d9/npm-debug.log). Output from build:

```sh
$ BITCORENODE_ASSUME_YES=true BITCORENODE_ENV=test npm install -g
...
libtool: link: /usr/bin/ranlib .libs/libbitcoind.a
libtool: link: ( cd ".libs" && rm -f "libbitcoind.la" && ln -s "../libbitcoind.la" "libbitcoind.la" )
make[2]: Leaving directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind/src'
make[1]: Leaving directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind/src'
make[1]: Entering directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind'
Creating the sha marker for the patching in libbitcoind...
Writing patch sha file to: "/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/bin/../cache/patch_sha.txt"
~/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind ~/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind
~/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/libbitcoind
Build finished successfully.
make: *** No rule to make target 'Release/obj.target/libbitcoind/src/libbitcoind.o', needed by 'Release/obj.target/bitcoind.node'.  Stop.
make: Entering directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/build'
make: Leaving directory '/.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.../.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.12-boot2docker
gyp ERR! command "/.../.nvm/versions/node/v4.2.2/bin/node" "/.../.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--debug=false" "rebuild"
gyp ERR! cwd /.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.1.12-boot2docker
npm ERR! argv "/.../.nvm/versions/node/v4.2.2/bin/node" "/.../.nvm/versions/node/v4.2.2/bin/npm" "install" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@1.0.1-dev install: `./bin/install`
npm ERR! Exit status 1
...
```

**Comment by posita** [comment]
Note that a *local* installation (i.e., *without* the `-g` argument passed to `npm install`) seems to work:

```sh
$ BITCORENODE_ASSUME_YES=true BITCORENODE_ENV=test npm install
... # works
```

**Comment by braydonf** [comment]
`BITCORENODE_ENV=test` no longer used.
