### ISSUE TITLE
Failed installing

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#420]
when I run `npm install bitcore-node` (even why I try to install it globaly with root) it fails to install and return this error:
```
Build finished successfully.
make: Entering directory '/home/elichai2/WebstormProjects/bitcore-test/node_modules/bitcore-node/build'
make: *** No rule to make target 'Release/obj.target/libbitcoind/src/libbitcoind.o', needed by 'Release/obj.target/bitcoind.node'.  Stop.
make: Leaving directory '/home/elichai2/WebstormProjects/bitcore-test/node_modules/bitcore-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "--debug=false" "rebuild"
gyp ERR! cwd /home/elichai2/WebstormProjects/bitcore-test/node_modules/bitcore-node
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! bitcore-node@2.1.0 install: `./bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@2.1.0 install script.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "bitcore-node"
npm ERR! cwd /home/elichai2/WebstormProjects/bitcore-test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/elichai2/WebstormProjects/bitcore-test/npm-debug.log
npm ERR! not ok code 0
```

here is the full `npm-debug.log`: http://paste.ubuntu.com/15409702/

**Comment by kleetus** [comment]
here is the issue: node -v v0.10.25

supported versions of node.js include 0.12.x and 4.x
