### ISSUE TITLE
bitcore from external hardrive

### ISSUE THREAD

**Issue by onepix** [bitpay/bitcore-node#429]
On a pc, I run a fully sync testnet ".bitcore" which is stored by default here : "~/" with the command
`bitcored`
Then, I backup the ".bitcore" folder to an external hard drive.
I plug it on my brand new raspberry pi and I'm looking for running bitcore into where it was stored.
In order to do so, I start the command bitcored directly from the directory where I stored it
> cd /media/pi/9C2696032695DF18/Projects
bitcored

accordingly to https://bitcore.io/guides/full-node/ _Start Sync_
But It's not working as you can see below :

> cd /media/pi/9C2696032695DF18/ANTOINE/
➜  ANTOINE cd .bitcore 
➜  .bitcore bitcored 
[2016-05-01T20:17:14.895Z] info: Starting bitcoind
[2016-05-01T20:17:14.914Z] error: uncaught exception: { [Error: EACCES: permission denied, mkdir '/Users'] errno: -13, code: 'EACCES', syscall: 'mkdir', path: '/Users' }
[2016-05-01T20:17:14.995Z] error: Error: EACCES: permission denied, mkdir '/Users'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/mkdirp/index.js:70:13)
    at sync (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/mkdirp/index.js:76:24)
    at sync (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/mkdirp/index.js:76:24)
    at Function.sync (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/mkdirp/index.js:76:24)
    at Bitcoin._loadConfiguration (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:44:12)
    at Bitcoin.start (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:155:8)
    at Node._startService (/home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/lib/node.js:189:11)
    at /home/pi/.nvm/versions/node/v4.4.3/lib/node_modules/bitcore/node_modules/bitcore-node/lib/node.js:232:12
[2016-05-01T20:17:14.997Z] info: Beginning shutdown
[2016-05-01T20:17:15.000Z] info: Stopping insight-ui (not started)
[2016-05-01T20:17:15.004Z] info: Stopping insight-api (not started)
[2016-05-01T20:17:15.007Z] info: Stopping web (not started)
[2016-05-01T20:17:15.008Z] info: Stopping address (not started)
[2016-05-01T20:17:15.008Z] info: Stopping db (not started)
[2016-05-01T20:17:15.009Z] info: Stopping bitcoind

Because you understand what I'm trying to do and also because I don't understand why there is "mkdir '/Users'"  (why it's necessary to create this directory?), I prefer asking for help

**Comment by onepix** [comment]
Oubs, 
> nvm use v4 

seems to have solve this :+1:

**Comment by onepix** [comment]
https://github.com/bitpay/bitcore/issues/1379
