### ISSUE TITLE
Failed to start services after shut down

### ISSUE THREAD

**Issue by vdidonato** [bitpay/bitcore-node#471]
My bitcore-node has been running for some weeks perfectly. 
At some point I had to restart it so I shut it down and try to restart it and I got the following error:

    [2016-07-23T13:25:11.729Z] warn: Verifying blocks...
    [2016-07-23T13:25:16.786Z] warn: Verifying blocks...
    [2016-07-23T13:25:21.794Z] warn: Verifying blocks...
    [2016-07-23T13:25:26.797Z] warn: Verifying blocks...
    [2016-07-23T13:25:26.817Z] error: Failed to start services
    [2016-07-23T13:25:26.875Z] error: RPCError: Verifying blocks...
    at Bitcoin._wrapRPCError (/home/<user>/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:449:13)
    at /home/<user>/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:780:28
    at IncomingMessage.<anonymous> (/home/<user>/mynode/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:107:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
    [2016-07-23T13:25:26.909Z] info: Beginning shutdown
    [2016-07-23T13:25:26.909Z] info: Stopping insight-api (not started)
    [2016-07-23T13:25:26.919Z] info: Stopping web (not started)
    [2016-07-23T13:25:26.920Z] info: Stopping bitcoind
    [2016-07-23T13:25:42.025Z] error: Failed to stop services: Error: bitcoind process did not exit

How do I fix it? I really don't know what to do...

**Comment by vdidonato** [comment]
I guess I just had to kill the bitcoind process.
Sorry for posting this but I was panicking..

**Comment by Levino** [comment]
In my case I have not bitcoin process running. It just fails. Any solution to this? Currently I fear the nuclear, is the only option. Through the db in the bin and restart sync.
