### ISSUE TITLE
Installation issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by docbitcoin** [bitpay/bitcore-node#497]
when installing bitcode exactly like described on a fresh installation of Ubuntu 16.04 I get the following error:

```
~$ npm install -g bitcore
/
> bitcore-node@3.1.3 preinstall /home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/bitcore/node_modules/bitcore-node
> ./scripts/download

Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/bitcoin-0.12.1-linux64.tar.gz
npm ERR! Linux 4.4.0-67-generic
npm ERR! argv "/home/bitcore/.nvm/versions/node/v4.8.0/bin/node" "/home/bitcore/.nvm/versions/node/v4.8.0/bin/npm" "install" "-g" "bitcore"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@3.1.3 preinstall: `./scripts/download`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the bitcore-node@3.1.3 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bitcore/npm-debug.log
```

What is strange: After the first installation attempt I do not have a npm-debug.log, after the second I do have it.

```
13787 verbose unlock done using /home/bitcore/.npm/_locks/insight-api-7ec2056a0920cacc.lock for /home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/bitcore/node_modules/insight-api
13788 info bitcore-node@3.1.3 Failed to exec preinstall script
13789 verbose unlock done using /home/bitcore/.npm/_locks/bitcore-node-4d2a35ce5a94981d.lock for /home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/bitcore/node_modules/bitcore-node
13790 verbose about to build /home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/bitcore
13791 verbose unlock done using /home/bitcore/.npm/_locks/bitcore-45f942b3c217b815.lock for /home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/bitcore
13792 verbose stack Error: bitcore-node@3.1.3 preinstall: `./scripts/download`
13792 verbose stack Exit status 8
13792 verbose stack     at EventEmitter.<anonymous> (/home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
13792 verbose stack     at emitTwo (events.js:87:13)
13792 verbose stack     at EventEmitter.emit (events.js:172:7)
13792 verbose stack     at ChildProcess.<anonymous> (/home/bitcore/.nvm/versions/node/v4.8.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
13792 verbose stack     at emitTwo (events.js:87:13)
13792 verbose stack     at ChildProcess.emit (events.js:172:7)
13792 verbose stack     at maybeClose (internal/child_process.js:854:16)
13792 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
13793 verbose pkgid bitcore-node@3.1.3
13794 verbose cwd /home/bitcore
13795 error Linux 4.4.0-67-generic
13796 error argv "/home/bitcore/.nvm/versions/node/v4.8.0/bin/node" "/home/bitcore/.nvm/versions/node/v4.8.0/bin/npm" "install" "-g" "bitcore"
13797 error node v4.8.0
13798 error npm  v2.15.11
13799 error code ELIFECYCLE
13800 error bitcore-node@3.1.3 preinstall: `./scripts/download`
13800 error Exit status 8
13801 error Failed at the bitcore-node@3.1.3 preinstall script './scripts/download'.
13801 error This is most likely a problem with the bitcore-node package,
13801 error not with npm itself.
13801 error Tell the author that this fails on your system:
13801 error     ./scripts/download
13801 error You can get information on how to open an issue for this project with:
13801 error     npm bugs bitcore-node
13801 error Or if that isn't available, you can get their info via:
13801 error
13801 error     npm owner ls bitcore-node
13801 error There is likely additional logging output above.
13802 verbose exit [ 1, true ]
13803 verbose unbuild lib/node_modules/bitcore/node_modules/bitcore-node
13804 info preuninstall bitcore-node@3.1.3
13805 info uninstall bitcore-node@3.1.3

```

**Comment by docbitcoin** [comment]
sorry, just saw it was this issue: [https://github.com/bitpay/bitcore/issues/1436](url)

**Comment by docbitcoin** [comment]
My system had no curl and python, that was the error.
You should add that to the install documentation as prerequisites IMHO.

**Comment by shravan-shandilya** [comment]
Install basic build requirements
```
sudo apt-get install build-essential
```

**Comment by miguelmorales85** [comment]
Same issue here. I will paste what I am having 

> pine@pine64:~$ npm install -g bitcore-node@latest
> |
> > bitcore-node@3.1.3 preinstall /home/pine/.nvm/versions/node/v4.8.5/lib/node_modules/bitcore-node
> > ./scripts/download
> 
> Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/
> npm ERR! Linux 3.10.105-pine64
> npm ERR! argv "/home/pine/.nvm/versions/node/v4.8.5/bin/node" "/home/pine/.nvm/versions/node/v4.8.5/bin/npm" "install" "-g" "bitcore-node@latest"
> npm ERR! node v4.8.5
> npm ERR! npm  v2.15.11
> npm ERR! code ELIFECYCLE
> 
> npm ERR! bitcore-node@3.1.3 preinstall: `./scripts/download`
> npm ERR! Exit status 22
> npm ERR! 
> npm ERR! Failed at the bitcore-node@3.1.3 preinstall script './scripts/download'.
> npm ERR! This is most likely a problem with the bitcore-node package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ./scripts/download
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs bitcore-node
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls bitcore-node
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/pine/npm-debug.log
