### ISSUE TITLE
RPC Error, Socket Hang up

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#503]
Hi,
I get this error:
```
RPCError: Bitcoin JSON-RPC: Request Error: socket hang up
    at Bitcoin._wrapRPCError (/root/re2Node/node_modules/bitcore-node/lib/services/bitcoind.js:449:13)
    at /root/re2Node/node_modules/bitcore-node/lib/services/bitcoind.js:1958:28
    at ClientRequest.<anonymous> (/root/re2Node/node_modules/bitcore-node/node_modules/bitcoind-rpc/lib/index.js:116:7)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketOnEnd (_http_client.js:300:9)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

how can I fix it?

**Comment by yinqianwu** [comment]
Same issue here. The issue probably is caused by too many RPC requests since I use setInterval() to request blockchain data. Anyone know how to solve it?
```
 Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at Socket.socketOnEnd (_http_client.js:421:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET'
```

**Comment by tangjielong** [comment]
why ,help me?
