### ISSUE TITLE
bitcored won't run on debian: popd and pushd don't exist in /bin/sh

### ISSUE THREAD

**Issue by toomim** [bitpay/bitcore-node#524]
I successfully installed the new bitcore on debian with node v8 with:

```shell
npm install -g bitcore@beta  
bitcored
```

However, when I run bitcored I get this error:
```
[2017-09-28T03:18:54.534Z] info: Starting insight-api
[2017-09-28T03:18:54.534Z] info: localhost-insight-api subscribe: p2p/transaction total: 2
[2017-09-28T03:18:54.534Z] info: localhost-insight-api subscribe: p2p/block total: 1
[2017-09-28T03:18:54.534Z] info: Starting insight-ui
[info] (net) Connected to 46.188.44.20:8333.
[2017-09-28T03:18:54.789Z] error: Failed to start services
[2017-09-28T03:18:54.789Z] error: Error: Command failed: pushd lib/node_modules/bitcore/node_modules/insight-ui/bitcore-node/../; npm run install-and-build; popd
/bin/sh: 1: pushd: not found
npm ERR! path package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     _logs/2017-09-28T03_18_54_778Z-debug.log
/bin/sh: 1: popd: not found

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

This appears to be because popd and pushd are operations only available in bash, and [debian does not run bash at /bin/sh](https://stackoverflow.com/a/5193087/440344).

**Comment by hawthornetr** [comment]
Did you solve this? I have it running, but no indexes are saving (block chain). Not sure why

**Comment by toomim** [comment]
I have not solved it. What did you do to work around the pushd/popd issue?
