### ISSUE TITLE
uncaught exception : [RangeError: index out of range 

### ISSUE THREAD

**Issue by HudsonProdigy** [bitpay/bitcore-node#543]
Hello,

I am not able to get insight api to work. it keeps crashing my node.
`[2018-01-18T22:41:14.859Z] error: uncaught exception: [RangeError: index out of range]
[2018-01-18T22:41:14.861Z] error: RangeError: index out of range
    at checkOffset (buffer.js:700:11)
    at Buffer.readUInt32LE (buffer.js:762:5)
    at BufferReader.readUInt32LE (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/insight-api/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
    at Transaction.fromBufferReader (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
    at Transaction.fromBuffer (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/insight-api/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:77:13)
    at Bitcoin.emit (events.js:169:7)
    at Bitcoin._zmqTransactionHandler (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/litecore-node/lib/services/bitcoind.js:639:10)
    at null.<anonymous> (/Users/coryhudson/TorontoCryptoClub/LitecoinDevelopment/LiveNetNode/node_modules/litecore-node/lib/services/bitcoind.js:713:12)
`

any help would be much appreciated.

Cheers

**Comment by saroar** [comment]
its dead group :)

**Comment by stefan52a** [comment]
see https://github.com/bitpay/insight/issues/842
