### ISSUE TITLE
Run the daemon and insight API on two distinct servers

### ISSUE THREAD

**Issue by ymatagne** [bitpay/bitcore-node#549]
Hello,

I'd like to run the bitcoin daemon and insight api on two servers : 
   - Server 1 : bitcoind
   - Server 2 : insight API

Do you know if it's possible ? I tried a lot of different configuration, but it don't work...

`{
    "network": "livenet",
    "port": 3001,
    "services": [
        "header",
        "insight-api",
        "insight-ui",
        "web",
        "p2p",
        "db",
        "block",
        "timestamp",
        "mempool",
        "transaction",
        "address",
        "fee"
    ],
    "servicesConfig": {
        "bitcoind": {
            "connect": [
                {
                    "rpchost": "DAEMON_URI",
                    "rpcport": 8332,
                    "rpcuser": "toto",
                    "rpcpassword": "toto",
                    "zmqpubhashtx": "tcp://DAEMON_URI:28332",
                    "zmqpubhashblock": "tcp://DAEMON_URI:28332",
                    "zmqpubrawblock": "tcp://DAEMON_URI:28332",
                    "zmqpubrawtx": "tcp://DAEMON_URI:28332"
                }
            ]
        },
        "insight-api": {
            "disableRateLimiter": true,
            "translateAddresses": process.env.translate,
            "cwdRequirePath": "node_modules/insight-api"
        },
        "insight-ui": {
            "cwdRequirePath": "node_modules/insight-ui"
        }
    }
}`

**Comment by qinfengling** [comment]
I am sure the Bitcore v5.0 can support it.
https://blog.bitpay.com/bitcore-v5/

You can find the doc here:
https://github.com/bitpay/bitcore-node/blob/master/docs/services/p2p.md

**Comment by ymatagne** [comment]
Yes, I know> So I tried to start with this :

- Server 1 :
 bitcoind -printtoconsole -port=8333 -server=1 -rpcallowip=0.0.0.0/0 -rpcuser=user -rpcpassword=password -rpcworkqueue=16000 -rpcport=8332 -uacomment=bitcore

- Server 2 : 
{
    "network": "livenet",
    "port": 3001,
    "services": [
        "header",
        "insight-api",
        "insight-ui",
        "web",
        "p2p",
        "db",
        "block",
        "timestamp",
        "mempool",
        "transaction",
        "address",
        "fee"
    ],
    "datadir": "/tmp",
    "servicesConfig": {
        "p2p": {
            "peers": [
                {
                    "ip": {
                        "v4": "bitcoind"
                    },
                    "port": 8333
                }
            ]
        },
        "insight-api": {
            "disableRateLimiter": true,
            "translateAddresses": true,
            "cwdRequirePath": "node_modules/insight-api"
        },
        "insight-ui": {
            "cwdRequirePath": "node_modules/insight-ui"
        }
    }
}


And it don't work :
[2018-02-22T01:03:28.037Z] info: Checked the current working directory for service: header
[2018-02-22T01:03:28.606Z] info: Checked the current working directory for service: node_modules/insight-ui
[2018-02-22T01:03:28.606Z] info: Checked the built-in path: lib/services, for service: insight-ui
[2018-02-22T01:03:28.608Z] info: Checked the current working directory for service: web
[2018-02-22T01:03:28.608Z] info: Checked the current working directory for service: p2p
[2018-02-22T01:03:28.684Z] info: Checked the current working directory for service: db
[2018-02-22T01:03:28.714Z] info: Checked the current working directory for service: block
[2018-02-22T01:03:28.721Z] info: Checked the current working directory for service: timestamp
[2018-02-22T01:03:28.724Z] info: Checked the current working directory for service: mempool
[2018-02-22T01:03:28.726Z] info: Checked the current working directory for service: transaction
[2018-02-22T01:03:28.728Z] info: Checked the current working directory for service: address
[2018-02-22T01:03:28.731Z] info: Checked the current working directory for service: fee
[2018-02-22T01:03:28.736Z] info: Using config: /api/bitcore-node.json
[2018-02-22T01:03:28.736Z] info: Using network: livenet
[2018-02-22T01:03:28.738Z] info: Starting p2p
[2018-02-22T01:03:28.789Z] info: Starting db
[2018-02-22T01:03:28.799Z] info: Starting header
[2018-02-22T01:03:28.807Z] info: Db Service: service prefix for: header is: 0001
[2018-02-22T01:03:28.814Z] info: Getting last header synced at height: 0
[2018-02-22T01:03:28.823Z] info: Starting timestamp
[2018-02-22T01:03:28.824Z] info: Db Service: service prefix for: timestamp is: 0002
[2018-02-22T01:03:28.824Z] info: Starting mempool
[2018-02-22T01:03:28.825Z] info: Db Service: service prefix for: mempool is: 0003
[2018-02-22T01:03:28.825Z] info: Mempool Service: mempool disabled until full sync.
[2018-02-22T01:03:28.826Z] info: Starting block
[2018-02-22T01:03:28.827Z] info: Db Service: service prefix for: block is: 0004
[2018-02-22T01:03:28.829Z] info: Block Service: loaded: 0 hashes from the index.
[2018-02-22T01:03:28.829Z] info: Starting transaction
[2018-02-22T01:03:28.830Z] info: Db Service: service prefix for: transaction is: 0005
[2018-02-22T01:03:28.831Z] info: Starting address
[2018-02-22T01:03:28.832Z] info: Db Service: service prefix for: address is: 0006
[2018-02-22T01:03:28.832Z] info: Starting web
[2018-02-22T01:03:28.863Z] info: Starting fee
[2018-02-22T01:03:28.864Z] info: Starting insight-api
[2018-02-22T01:03:28.866Z] info: localhost-insight-api subscribe: mempool/transaction total: 1
[2018-02-22T01:03:28.866Z] info: localhost-insight-api subscribe: block/block total: 1
[2018-02-22T01:03:28.866Z] info: Starting insight-ui
[2018-02-22T01:03:28.868Z] info: Bitcore Node ready
[2018-02-22T01:03:28.868Z] info: Connecting to p2p network.
[2018-02-22T01:03:28.978Z] info: Connected to peer: bitcoind, network: livenet, version: 70015, subversion: /Satoshi:0.15.1(bitcore)/, status: ready, port: 8333, best height: 108267
[2018-02-22T01:03:28.979Z] info: Header Service: Best Height is: 108267
[2018-02-22T01:03:28.980Z] info: localhost-header unsubscribe: p2p/headers total: 0
[2018-02-22T01:03:28.980Z] info: localhost-header unsubscribe: p2p/block total: 0
[2018-02-22T01:03:28.981Z] info: Header Service: Gathering: 108267 header(s) from the peer-to-peer network.
[2018-02-22T01:03:28.982Z] info: Header Service: subscribed to p2p headers.
[2018-02-22T01:03:28.982Z] info: localhost-header subscribe: p2p/headers total: 1
[2018-02-22T01:03:29.854Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:03:29.856Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:03:29.856Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:03:29.857Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:33.438Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:33.473Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks?limit=5" 200 - 10.835 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:33.482Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 4.904 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:33.483Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:34.909Z] info: ::ffff:172.17.0.1 web socket disconnect
[2018-02-22T01:10:34.919Z] info: ::ffff:172.17.0.1 unsubscribe: p2p/transaction total: 0
[2018-02-22T01:10:34.920Z] info: ::ffff:172.17.0.1 unsubscribe: p2p/block total: 0
[2018-02-22T01:10:34.926Z] info: ::ffff:172.17.0.1 unsubscribe: p2p/headers total: 1
[2018-02-22T01:10:34.926Z] info: ::ffff:172.17.0.1 unsubscribe: header/block total: 0
[2018-02-22T01:10:34.927Z] info: ::ffff:172.17.0.1 unsubscribe: mempool/transaction total: 1
[2018-02-22T01:10:34.927Z] info: ::ffff:172.17.0.1 unsubscribe: block/block total: 1
[2018-02-22T01:10:35.154Z] info: ::ffff:172.17.0.1 "GET /insight-api/version" 304 - 9.585 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:35.241Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks?limit=5" 200 - 4.097 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:35.277Z] info: ::ffff:172.17.0.1 "GET /insight-api/sync" 304 - 4.495 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:35.391Z] info: ::ffff:172.17.0.1 "GET /insight-api/status?q=getInfo" 304 - 94.635 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:35.472Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 0.528 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:35.482Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:35.496Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:35.497Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:35.508Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:35.508Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:35.508Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:35.756Z] info: ::ffff:172.17.0.1 "GET /insight-api/currency" 200 43 356.442 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 




[2018-02-22T01:10:43.637Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks" 200 - 1.130 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:43.670Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:43.700Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 0.568 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.653Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks?limit=5" 200 - 0.819 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.654Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:51.661Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 0.354 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.677Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:11:35.073Z] error: Error: block not in index
    at /api/node_modules/insight-api/lib/blocks.js:79:41
    at /api/node_modules/bitcore-node/lib/services/block/index.js:123:14
    at /api/node_modules/bitcore-node/lib/services/block/index.js:491:16
    at /api/node_modules/bitcore-node/lib/services/header/index.js:617:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.076Z] error: Error: block not in index
    at /api/node_modules/insight-api/lib/blocks.js:79:41
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
[2018-02-22T01:11:35.075Z] info: ::ffff:172.17.0.1 "GET /insight-api/block/108267" 503 18 3.207 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.084Z] error: uncaught exception: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:170:12)
    at Common.handleErrors (/api/node_modules/insight-api/lib/common.js:22:23)
    at /api/node_modules/insight-api/lib/blocks.js:79:28
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.085Z] error: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:170:12)
    at Common.handleErrors (/api/node_modules/insight-api/lib/common.js:22:23)
    at /api/node_modules/insight-api/lib/blocks.js:79:28
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.089Z] info: Beginning shutdown
[2018-02-22T01:11:35.089Z] info: P2P Service: disconnecting pool and peers. SIGINT issued, system shutdown initiated
[2018-02-22T01:11:35.106Z] info: Disconnected from peer: bitcoind
[2018-02-22T01:11:35.106Z] warn: Node is stopping, gently closing the database. Please wait, this could take a while.
[2018-02-22T01:11:35.107Z] info: Stopping insight-ui
[2018-02-22T01:11:35.107Z] info: Stopping insight-api
[2018-02-22T01:11:35.108Z] info: Stopping fee
[2018-02-22T01:11:35.108Z] info: Stopping web
[2018-02-22T01:11:35.109Z] info: Stopping address
[2018-02-22T01:11:35.110Z] info: ::ffff:172.17.0.1 "GET /insight-api/tx/108267" 404 9 2.624 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:11:35.110Z] info: Stopping transaction
[2018-02-22T01:11:35.111Z] info: Stopping block
[2018-02-22T01:11:35.111Z] info: Stopping mempool
[2018-02-22T01:11:35.111Z] info: Stopping timestamp
[2018-02-22T01:11:35.111Z] info: Stopping header
[2018-02-22T01:11:35.111Z] info: Stopping db
[addresses.js.130] Error: Non-base58 character
    at Object.decode (/api/node_modules/insight-api/node_modules/base-x/index.js:83:11)
    at Function.Base58.decode (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/encoding/base58.js:48:26)
    at Function.Base58Check.decode (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/encoding/base58check.js:45:31)
    at Function.Address._transformString (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:283:35)
    at Address._classifyArguments (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:107:20)
    at new Address (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:73:19)
    at /api/node_modules/insight-api/lib/addresstranslator.js:34:16
    at Function.map (/api/node_modules/insight-api/node_modules/lodash/dist/lodash.js:3509:27)
    at Function.AddressTranslator.translate (/api/node_modules/insight-api/lib/addresstranslator.js:33:16)
    at Function.AddressTranslator.translateInput (/api/node_modules/insight-api/lib/addresstranslator.js:46:15)
[2018-02-22T01:11:35.137Z] info: ::ffff:172.17.0.1 "GET /insight-api/addr/108267/?noTxList=1" 400 52 13.459 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:11:35.138Z] info: Stopping p2p

[2018-02-22T01:10:43.637Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks" 200 - 1.130 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:43.670Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:10:43.700Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 0.568 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.653Z] info: ::ffff:172.17.0.1 "GET /insight-api/blocks?limit=5" 200 - 0.819 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.654Z] info: ::ffff:172.17.0.1 web socket subscribe: inv
[2018-02-22T01:10:51.661Z] info: ::ffff:172.17.0.1 "GET /insight-api/peer" 304 - 0.354 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:10:51.677Z] info: ::ffff:172.17.0.1 web socket subscribe: sync
[2018-02-22T01:11:35.073Z] error: Error: block not in index
    at /api/node_modules/insight-api/lib/blocks.js:79:41
    at /api/node_modules/bitcore-node/lib/services/block/index.js:123:14
    at /api/node_modules/bitcore-node/lib/services/block/index.js:491:16
    at /api/node_modules/bitcore-node/lib/services/header/index.js:617:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.076Z] error: Error: block not in index
    at /api/node_modules/insight-api/lib/blocks.js:79:41
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
[2018-02-22T01:11:35.075Z] info: ::ffff:172.17.0.1 "GET /insight-api/block/108267" 503 18 3.207 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.084Z] error: uncaught exception: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:170:12)
    at Common.handleErrors (/api/node_modules/insight-api/lib/common.js:22:23)
    at /api/node_modules/insight-api/lib/blocks.js:79:28
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.085Z] error: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/api/node_modules/bitcore-node/node_modules/express/lib/response.js:170:12)
    at Common.handleErrors (/api/node_modules/insight-api/lib/common.js:22:23)
    at /api/node_modules/insight-api/lib/blocks.js:79:28
    at /api/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /api/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /api/node_modules/bitcore-node/node_modules/levelup/lib/levelup.js:159:14
[2018-02-22T01:11:35.089Z] info: Beginning shutdown
[2018-02-22T01:11:35.089Z] info: P2P Service: disconnecting pool and peers. SIGINT issued, system shutdown initiated
[2018-02-22T01:11:35.106Z] info: Disconnected from peer: bitcoind
[2018-02-22T01:11:35.106Z] warn: Node is stopping, gently closing the database. Please wait, this could take a while.
[2018-02-22T01:11:35.107Z] info: Stopping insight-ui
[2018-02-22T01:11:35.107Z] info: Stopping insight-api
[2018-02-22T01:11:35.108Z] info: Stopping fee
[2018-02-22T01:11:35.108Z] info: Stopping web
[2018-02-22T01:11:35.109Z] info: Stopping address
[2018-02-22T01:11:35.110Z] info: ::ffff:172.17.0.1 "GET /insight-api/tx/108267" 404 9 2.624 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:11:35.110Z] info: Stopping transaction
[2018-02-22T01:11:35.111Z] info: Stopping block
[2018-02-22T01:11:35.111Z] info: Stopping mempool
[2018-02-22T01:11:35.111Z] info: Stopping timestamp
[2018-02-22T01:11:35.111Z] info: Stopping header
[2018-02-22T01:11:35.111Z] info: Stopping db
[addresses.js.130] Error: Non-base58 character
    at Object.decode (/api/node_modules/insight-api/node_modules/base-x/index.js:83:11)
    at Function.Base58.decode (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/encoding/base58.js:48:26)
    at Function.Base58Check.decode (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/encoding/base58check.js:45:31)
    at Function.Address._transformString (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:283:35)
    at Address._classifyArguments (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:107:20)
    at new Address (/api/node_modules/insight-api/node_modules/bitcore-lib-cash/lib/address.js:73:19)
    at /api/node_modules/insight-api/lib/addresstranslator.js:34:16
    at Function.map (/api/node_modules/insight-api/node_modules/lodash/dist/lodash.js:3509:27)
    at Function.AddressTranslator.translate (/api/node_modules/insight-api/lib/addresstranslator.js:33:16)
    at Function.AddressTranslator.translateInput (/api/node_modules/insight-api/lib/addresstranslator.js:46:15)
[2018-02-22T01:11:35.137Z] info: ::ffff:172.17.0.1 "GET /insight-api/addr/108267/?noTxList=1" 400 52 13.459 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36" 
[2018-02-22T01:11:35.138Z] info: Stopping p2p

**Comment by ymatagne** [comment]
I think, Insight API is connected to the daemon : 
[2018-02-22T01:03:28.978Z] info: Connected to peer: bitcoind, network: livenet, version: 70015, subversion: /Satoshi:0.15.1(bitcore)/, status: ready, port: 8333, best height: 108267
[2018-02-22T01:03:28.979Z] info: Header Service: Best Height is: 108267

But, When I look for get block or transaction, insigh api dont found this.
