### ISSUE TITLE
Cannot install bitcore-node npm in CentOS server

### ISSUE THREAD

**Issue by namanjd** [bitpay/bitcore-node#569]
`npm install bitcore-node --save`

`> bitcore-node@3.1.3 preinstall /root/node_modules/bitcore-node
> ./scripts/download

Downloading bitcoin: https://github.com/bitpay/bitcoin/releases/download/v0.12.1-bitcore-4/bitcoin-0.12.1-linux64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   619    0   619    0     0   1313      0 --:--:-- --:--:-- --:--:--  1314
100 24.6M  100 24.6M    0     0  1121k      0  0:00:22  0:00:22 --:--:-- 1189k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604    0   604    0     0   1215      0 --:--:-- --:--:-- --:--:--  1217
100  1154  100  1154    0     0   1271      0 --:--:-- --:--:-- --:--:--  1271
Unpacking bitcoin distribution
bitcoin-0.12.1/
bitcoin-0.12.1/bin/
bitcoin-0.12.1/bin/bitcoin-cli
bitcoin-0.12.1/bin/bitcoind
bitcoin-0.12.1/bin/bitcoin-qt
bitcoin-0.12.1/bin/bitcoin-tx
bitcoin-0.12.1/bin/test_bitcoin
bitcoin-0.12.1/bin/wallet-utility
bitcoin-0.12.1/include/
bitcoin-0.12.1/include/bitcoinconsensus.h
bitcoin-0.12.1/lib/
bitcoin-0.12.1/lib/libbitcoinconsensus.so
bitcoin-0.12.1/lib/libbitcoinconsensus.so.0
bitcoin-0.12.1/lib/libbitcoinconsensus.so.0.0.0

> bufferutil@1.2.1 install /root/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/root/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/root/node_modules/bufferutil/build'

> utf-8-validate@1.2.2 install /root/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/root/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/root/node_modules/utf-8-validate/build'

> zmq@2.15.3 install /root/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/root/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/root/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-862.3.2.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/zmq
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     `/root/.npm/_logs/2018-06-29T06_24_24_456Z-debug.log`

**Comment by troshkin** [comment]
Try to install prerequisites [https://bitcore.io/guides/full-node](https://bitcore.io/guides/full-node)
