### ISSUE TITLE
LevelUPError: Installed version of LevelDOWN (1.0.2) does not match required version (~0.10.0)

### ISSUE THREAD

**Issue by kentdome** [bitpay/bitcore-node#61]
sudo node index.js

/bitcore-node/node_modules/levelup/lib/util.js:59
    throw new LevelUPError(
          ^
LevelUPError: Installed version of LevelDOWN (1.0.2) does not match required version (~0.10.0)
    at getLevelDOWN (/bitcore-node/node_modules/levelup/lib/util.js:59:11)
    at LevelUP.open (/bitcore-node/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/bitcore-node/node_modules/levelup/lib/levelup.js:86:8)
    at Function.BitcoreNode.create (/bitcore-node/lib/node.js:52:5)
    at Object.<anonymous> (/bitcore-node/index.js:15:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by maraoz** [comment]
Many have reported this same problem, but I'm unable to reproduce it. 
Can you give me the output of running this in your host? `node -v && npm -v && cat node_modules/*/package.json | grep "\"version\""`

**Comment by kentdome** [comment]
Remove the entire bitcore-node directory and grabbed the latest bits from github again -- no LevelUPError this time.

	node -v && npm -v && cat node_modules/*/package.json | grep "\"version\""
	v0.10.25
	1.3.10
	  "version": "0.9.0",
	  "version": "0.2.1",
	  "version": "0.5.4",
	  "version": "0.13.0",
	  "version": "0.11.7",
	  "version": "2.9.25",
	  "version": "1.12.3",
	  "version": "0.1.1",
	  "version": "2.1.2",
	  "version": "2.3.0",
	  "version": "1.4.3",
	  "version": "1.12.0",
	  "version": "2.6.0",
	  "version": "0.4.14",
	  "version": "4.11.1",
	  "version": "5.0.5",
	  "version": "3.8.11",
	  "version": "3.3.0",
	  "version": "1.0.2",
	  "version": "0.19.0",
	  "version": "1.0.0",
	  "version": "2.2.4",
	  "version": "2.5.1",
	  "version": "1.5.2",
	  "version": "2.55.0",
	  "version": "5.2.0",
	  "version": "1.14.1",
	  "version": "1.0.6",
	  "version": "0.15.0",
	  "version": "1.0.0",

However, we've set the yaml config files and exported environment vars i..e BITCOIND_USER etc for good measure yet we fail to get ti going:

/bitcore-node/node_modules/config/lib/config.js:177
    throw new Error('Configuration property "' + property + '" is not defined'
          ^
Error: Configuration property "BitcoreHTTP.BitcoreNode" is not defined
    at Config.get (/bitcore-node/node_modules/config/lib/config.js:177:11)
    at Object.<anonymous> (/bitcore-node/index.js:13:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3


still missing some bits?
