### ISSUE TITLE
Configuration property "BitcoreHTTP.BitcoreNode" is not defined

### ISSUE THREAD

**Issue by kentdome** [bitpay/bitcore-node#62]
Fresh install, default.yaml configured but getting:

/bitcore-node/node_modules/config/lib/config.js:177
throw new Error('Configuration property "' + property + '" is not defined'
^
Error: Configuration property "BitcoreHTTP.BitcoreNode" is not defined
at Config.get (/bitcore-node/node_modules/config/lib/config.js:177:11)
at Object. (/bitcore-node/index.js:13:24)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3

**Comment by ShaliDaliHaliDa** [comment]
I am getting Error: More than one instance of bitcore found with different versions: v0.11.7 and v0.12.1. Make sure there are no version conflicts between package.json files of your dependencies. This could also happen when a package depends on a git repository.

**Comment by maraoz** [comment]
should be solved now. Please reopen if issue still happens.
