### ISSUE TITLE
Error: Cannot find module 'eventemitter2'

### ISSUE THREAD

**Issue by kentdome** [bitpay/bitcore-node#71]
clean vm, fresh install...

npm start

> bitcore-node@0.1.0 start /data/bitcore-node
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'eventemitter2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/data/bitcore-node/lib/node.js:4:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by kentdome** [comment]
Never mind, fresh git pull fixed this issue.
