### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kentdome** [bitpay/bitcore-node#73]
Attempting to sync, it get's to about 60% and crashes. Attempting to restart eventually yields:

All headers fetched, total = 230926
starting network monitor
No blocks yet
network monitor disconnected
network monitor disconnected
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at Output.toBufferWriter (/data/bitcore-node/node_modules/bitcore/lib/transaction/output.js:147:31)
    at /data/bitcore-node/node_modules/bitcore/lib/transaction/transaction.js:272:12
    at Function.forEach (/data/bitcore-node/node_modules/bitcore/node_modules/lodash/dist/lodash.js:3297:15)
    at Transaction.toBufferWriter (/data/bitcore-node/node_modules/bitcore/lib/transaction/transaction.js:271:5)
    at Transaction.toBuffer (/data/bitcore-node/node_modules/bitcore/lib/transaction/transaction.js:261:15)
    at Transaction._getHash (/data/bitcore-node/node_modules/bitcore/lib/transaction/transaction.js:130:33)
    at Transaction.hashProperty.get (/data/bitcore-node/node_modules/bitcore/lib/transaction/transaction.js:105:34)
    at Object._.extend.getBlockForTransaction (/data/bitcore-node/lib/services/transaction.js:73:45)
    at TransactionService._confirmTransaction (/data/bitcore-node/lib/services/transaction.js:177:16)
    at /data/bitcore-node/lib/services/block.js:298:40
    at Array.map (native)
    at /data/bitcore-node/lib/services/block.js:297:45
From previous event:
    at BlockService.confirm (/data/bitcore-node/lib/services/block.js:285:21)
    at /data/bitcore-node/lib/node.js:118:36
    at Array.map (native)
    at Promise.each.then.then.deleteHeight (/data/bitcore-node/lib/node.js:117:56)
From previous event:
    at /data/bitcore-node/lib/node.js:116:8
    at /data/bitcore-node/lib/eventbus.js:26:14
    at Array.map (native)
    at processEvent (/data/bitcore-node/lib/eventbus.js:25:52)
    at /data/bitcore-node/lib/eventbus.js:50:14
    at process._tickCallback (node.js:448:13)
From previous event:
    at EventBus.process (/data/bitcore-node/lib/eventbus.js:48:6)
    at Peer.<anonymous> (/data/bitcore-node/lib/networkmonitor.js:59:14)
    at Peer.emit (events.js:95:17)
    at Peer._readMessage (/data/bitcore-node/node_modules/bitcore-p2p/lib/peer.js:221:10)
    at Socket.<anonymous> (/data/bitcore-node/node_modules/bitcore-p2p/lib/peer.js:167:10)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

**Comment by braydonf** [comment]
Closing, as no longer relevant.
